name: proyecto
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_rating_bar: ^4.0.1
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0
  permission_handler: ^11.0.1
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  firebase_storage: ^11.4.0
  firebase_database: ^10.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true