// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYBOF23FRV7BPL6GQOcrmippIpIL3x--0',
    appId: '1:461313390450:web:0f78482ad7f6a48aa30feb',
    messagingSenderId: '461313390450',
    projectId: 'moviles-cafes',
    authDomain: 'moviles-cafes.firebaseapp.com',
    storageBucket: 'moviles-cafes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv2i4a6HeiO5Jzp1u7S6Wi0U8Mz2XauYs',
    appId: '1:461313390450:android:e6dfca70ca468384a30feb',
    messagingSenderId: '461313390450',
    projectId: 'moviles-cafes',
    storageBucket: 'moviles-cafes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCewNadXRlJ2O6WfbKNIOe_MBvFfa8TwuY',
    appId: '1:461313390450:ios:46ab58b6b71292f9a30feb',
    messagingSenderId: '461313390450',
    projectId: 'moviles-cafes',
    storageBucket: 'moviles-cafes.appspot.com',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCewNadXRlJ2O6WfbKNIOe_MBvFfa8TwuY',
    appId: '1:461313390450:ios:3fd9d9813976a7e5a30feb',
    messagingSenderId: '461313390450',
    projectId: 'moviles-cafes',
    storageBucket: 'moviles-cafes.appspot.com',
    iosBundleId: 'com.example.proyecto.RunnerTests',
  );
}
